$(document).ready(function () {
  $('#c1').click(function (e) {
    $('#r1').css('display', 'block')
    $('#r2').css('display', 'none')
    $('#r3').css('display', 'none')
    $('#r4').css('display', 'none')
    $('#r5').css('display', 'none')
    $('#r6').css('display', 'none')
  })
  $('#c2').click(function (e) {
    $('#r1').css('display', 'none')
    $('#r2').css('display', 'block')
    $('#r3').css('display', 'none')
    $('#r4').css('display', 'none')
    $('#r5').css('display', 'none')
    $('#r6').css('display', 'none')
  })
  $('#c3').click(function (e) {
    $('#r1').css('display', 'none')
    $('#r2').css('display', 'none')
    $('#r3').css('display', 'block')
    $('#r4').css('display', 'none')
    $('#r5').css('display', 'none')
    $('#r6').css('display', 'none')
  })
  $('#c4').click(function (e) {
    $('#r1').css('display', 'none')
    $('#r2').css('display', 'none')
    $('#r3').css('display', 'none')
    $('#r4').css('display', 'block')
    $('#r5').css('display', 'none')
    $('#r6').css('display', 'none')
  })
  $('#c5').click(function (e) {
    $('#r1').css('display', 'none')
    $('#r2').css('display', 'none')
    $('#r3').css('display', 'none')
    $('#r4').css('display', 'none')
    $('#r5').css('display', 'block')
    $('#r6').css('display', 'none')
  })
  $('#c6').click(function (e) {
    $('#r1').css('display', 'none')
    $('#r2').css('display', 'none')
    $('#r3').css('display', 'none')
    $('#r4').css('display', 'none')
    $('#r5').css('display', 'none')
    $('#r6').css('display', 'block')
  })
})
